const en = {
  packs: 'Resource packs',
  noPacks: 'This instance has no resource packs yet.',
  pick: 'Pick a resource pack on the left.',
  intro: 'Turn off parts of this pack. For those parts Minecraft then uses the packs below it, or the vanilla look.',
  loading: 'Reading the pack…',
  unreadable: 'This pack could not be read: {reason}',
  edited: 'edited',
  off: 'off',
  copyOf: 'Edited copy of {name}. Changes here replace that copy.',
  sourceMissing: 'Edited copy of {name}, which is no longer here. Parts turned off earlier cannot come back.',
  search: 'Search parts',
  onlyOff: 'Only turned off',
  noMatch: 'Nothing matches.',
  partOff: 'Off',
  countOff: '{off} off of {total}',
  replaces: 'Saving replaces {name}.',
  summary: '{off} of {total} parts turned off',
  nothingOff: 'Everything is on',
  kept: 'pack.mcmeta, pack.png and other files outside assets always stay.',
  reset: 'Undo changes',
  save: 'Save',
  saving: 'Saving…',
  saved: 'Saved as {name}',
  savedHint: 'The original was turned off and the copy took its place in the game.',
  running: 'Close the game first. It keeps its resource packs open.',
  failed: 'Could not save',
  discard: 'Leave without saving your changes to this pack?',
  general: 'General',
  categories: {
    blocks: 'Blocks',
    items: 'Items',
    entities: 'Mobs and entities',
    armor: 'Armor and trims',
    gui: 'Interface',
    fonts: 'Fonts',
    particles: 'Particles',
    environment: 'Sky and environment',
    effects: 'Effect icons',
    paintings: 'Paintings',
    misc: 'Other textures',
    sounds: 'Sounds',
    languages: 'Languages',
    texts: 'Texts',
    shaders: 'Shaders and materials',
    optifine: 'OptiFine extras',
    other: 'Everything else',
  },
}

const pl = {
  packs: 'Paczki zasobów',
  noPacks: 'Ta instancja nie ma jeszcze paczek zasobów.',
  pick: 'Wybierz paczkę zasobów po lewej.',
  intro: 'Wyłącz części tej paczki. Dla nich Minecraft użyje paczek leżących niżej albo wyglądu podstawowego.',
  loading: 'Czytam paczkę…',
  unreadable: 'Nie udało się odczytać tej paczki: {reason}',
  edited: 'edytowana',
  off: 'wyłączona',
  copyOf: 'Edytowana kopia paczki {name}. Zmiany tutaj podmieniają tę kopię.',
  sourceMissing: 'Edytowana kopia paczki {name}, której już tu nie ma. Wcześniej wyłączone części nie wrócą.',
  search: 'Szukaj części',
  onlyOff: 'Tylko wyłączone',
  noMatch: 'Nic nie pasuje.',
  partOff: 'Wył.',
  countOff: '{off} wył. z {total}',
  replaces: 'Zapis podmieni {name}.',
  summary: 'Wyłączone części: {off} z {total}',
  nothingOff: 'Wszystko jest włączone',
  kept: 'pack.mcmeta, pack.png i inne pliki spoza assets zostają zawsze.',
  reset: 'Cofnij zmiany',
  save: 'Zapisz',
  saving: 'Zapisuję…',
  saved: 'Zapisano jako {name}',
  savedHint: 'Oryginał został wyłączony, a kopia zajęła jego miejsce w grze.',
  running: 'Najpierw zamknij grę. Trzyma swoje paczki zasobów otwarte.',
  failed: 'Nie udało się zapisać',
  discard: 'Wyjść bez zapisywania zmian w tej paczce?',
  general: 'Ogólne',
  categories: {
    blocks: 'Bloki',
    items: 'Przedmioty',
    entities: 'Moby i byty',
    armor: 'Zbroje i wykończenia',
    gui: 'Interfejs',
    fonts: 'Czcionki',
    particles: 'Cząsteczki',
    environment: 'Niebo i otoczenie',
    effects: 'Ikony efektów',
    paintings: 'Obrazy',
    misc: 'Inne tekstury',
    sounds: 'Dźwięki',
    languages: 'Języki',
    texts: 'Teksty',
    shaders: 'Shadery i materiały',
    optifine: 'Dodatki OptiFine',
    other: 'Pozostałe',
  },
}

export const LANGUAGES = { en, pl }

export function translator(locale) {
  const table = LANGUAGES[String(locale).slice(0, 2)] ?? en
  return (key, params = {}) => {
    const text = key.split('.').reduce((node, part) => node?.[part], table) ?? key.split('.').reduce((node, part) => node?.[part], en) ?? key
    return String(text).replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? ''))
  }
}
